export {default as PostForm} from './PostForm'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as NavBar} from './NavBar'
export {default as AllPosts} from './AllPosts'
export {default as SinglePost} from './SinglePost'
